/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-variant": "#e1e2ec",
        "outline-variant": "#c2c6d6",
        "on-surface-variant": "#424754",
        "tertiary-container": "#b75b00",
        "on-tertiary-fixed-variant": "#723600",
        "secondary-fixed": "#dbe3ec",
        "primary-fixed": "#d8e2ff",
        "surface-container-high": "#e6e7f2",
        "outline": "#727785",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container": "#ecedf7",
        "tertiary": "#924700",
        "tertiary-fixed": "#ffdcc6",
        "on-tertiary-fixed": "#311400",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9ff",
        "on-secondary-container": "#5d656d",
        "tertiary-fixed-dim": "#ffb786",
        "on-surface": "#191b23",
        "on-tertiary-container": "#fffbff",
        "surface-container-highest": "#e1e2ec",
        "background": "#f9f9ff",
        "secondary-container": "#dbe3ec",
        "surface-container-low": "#f2f3fd",
        "inverse-on-surface": "#eff0fa",
        "error": "#ba1a1a",
        "surface-dim": "#d8d9e3",
        "secondary-fixed-dim": "#bfc7d0",
        "on-secondary-fixed": "#151c23",
        "surface-tint": "#005ac2",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#40484f",
        "on-secondary": "#ffffff",
        "primary-container": "#2170e4",
        "on-primary": "#ffffff",
        "surface": "#f9f9ff",
        "inverse-surface": "#2e3038",
        "on-primary-fixed-variant": "#004395",
        "inverse-primary": "#adc6ff",
        "on-primary-container": "#fefcff",
        "primary": "#0058be",
        "on-background": "#191b23",
        "on-primary-fixed": "#001a42",
        "secondary": "#575f67",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#adc6ff"
      },
      "fontFamily": {
        "sans": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
      }
    },
  },
  plugins: [],
}
